# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'SimpleRealmChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleRealmChat
  pod 'RealmSwift', '=10.1.0'

end
